# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRSWW():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://localhost:3000/")
    self.driver.find_element(By.LINK_TEXT, "Zaloguj").click()
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.NAME, "login").send_keys("Ala")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("MaKota")
    self.driver.find_element(By.CSS_SELECTOR, ".log").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h5").text == "Zalogowano jako: Ala"
  
  def test_logout(self):
    self.driver.get("http://localhost:3000/")
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-toggle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "Zaloguj się"
  
  def test_purchase(self):
    self.driver.get("http://localhost:3000/")
    self.driver.find_element(By.LINK_TEXT, "Zaloguj").click()
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.NAME, "login").send_keys("Kevin")
    self.driver.find_element(By.NAME, "password").send_keys("SamWDomu")
    self.driver.find_element(By.CSS_SELECTOR, ".log").click()
    self.driver.find_element(By.LINK_TEXT, "Strona główna").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > select")
    dropdown.find_element(By.XPATH, "//option[. = 'Hiszpania']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > input").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(9)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(1) > .search").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > input").send_keys("01")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > select")
    dropdown.find_element(By.XPATH, "//option[. = 'Samolot']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
    self.driver.find_element(By.NAME, "promotionCode").click()
    self.driver.find_element(By.NAME, "promotionCode").send_keys("abcd")
    self.driver.find_element(By.CSS_SELECTOR, ".reserve:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".reserve:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".reserve:nth-child(3)").click()
    self.driver.find_element(By.NAME, "cardNumber").click()
    self.driver.find_element(By.NAME, "cardNumber").send_keys("111111111111")
    self.driver.find_element(By.NAME, "CVV").click()
    self.driver.find_element(By.NAME, "CVV").send_keys("222")
    self.driver.find_element(By.NAME, "fullName").click()
    self.driver.find_element(By.NAME, "fullName").send_keys("Kevin SamWDomu")
    self.driver.find_element(By.NAME, "expDate").click()
    self.driver.find_element(By.NAME, "expDate").send_keys("11/23")
    self.driver.find_element(By.CSS_SELECTOR, ".log").click()
    time.sleep(10)
    assert self.driver.find_element(By.CSS_SELECTOR, "h5").text == "Płatność przeszła pomyślnie. Oferta zarezerwowana."
  
